__loadLesson({
  "lesson": "ess",
  "title": "필수 어휘 (교육부 2022 · 교과서 외)",
  "version": "1.0",
  "build_date": "2026-07-12",
  "build_note": "2차 필수어휘: 교육부 2022 개정 [별책14] 기본어휘 **표(중·고 공통)에서 중2 고빈도·일상어 선별. 기존 341어(1차 교과서+VD-L1~4)·교과서 본문과 중복 0. 예문은 중2 수준 자체 제작.",
  "core_sentences": [],
  "grammar_rules": [],
  "questions": [],
  "vocab_drill": [
    {
      "id": "VD-ESS-001",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "sentence",
      "pos": "명사",
      "meaning": "문장",
      "example": "Write one sentence about your day.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "써 봐 / 한 **문장**을 / 네 하루에 대해.",
      "example_ko": "네 하루에 대해 한 **문장** 써 봐."
    },
    {
      "id": "VD-ESS-002",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "essay",
      "pos": "명사",
      "meaning": "글, 에세이",
      "example": "I wrote an essay about my hero.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 썼다 / **글(에세이)**을 / 내 영웅에 대해.",
      "example_ko": "나는 내 영웅에 대한 **글(에세이)**을 썼어."
    },
    {
      "id": "VD-ESS-003",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "speech",
      "pos": "명사",
      "meaning": "연설",
      "example": "He gave a great speech at school.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그는 했다 / 훌륭한 **연설**을 / 학교에서.",
      "example_ko": "그는 학교에서 멋진 **연설**을 했어."
    },
    {
      "id": "VD-ESS-004",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "poem",
      "pos": "명사",
      "meaning": "시",
      "example": "She read a short poem to us.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 읽었다 / 짧은 **시**를 / 우리에게.",
      "example_ko": "그녀는 우리에게 짧은 **시**를 읽어 줬어."
    },
    {
      "id": "VD-ESS-005",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "graph",
      "pos": "명사",
      "meaning": "그래프",
      "example": "The graph shows our test scores.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 **그래프**는 / 보여 준다 / 우리 시험 점수를.",
      "example_ko": "그 **그래프**는 우리 시험 점수를 보여 줘."
    },
    {
      "id": "VD-ESS-006",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "chart",
      "pos": "명사",
      "meaning": "도표, 차트",
      "example": "Look at the chart on the wall.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "봐 / 그 **도표**를 / 벽에 있는.",
      "example_ko": "벽에 있는 **도표**를 봐."
    },
    {
      "id": "VD-ESS-007",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "triangle",
      "pos": "명사",
      "meaning": "삼각형",
      "example": "A triangle has three sides.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**삼각형**은 / 가진다 / 세 변을.",
      "example_ko": "**삼각형**은 변이 세 개야."
    },
    {
      "id": "VD-ESS-008",
      "unit": "필수",
      "theme": "학교·공부·글",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "schedule",
      "pos": "명사",
      "meaning": "일정, 시간표",
      "example": "My schedule is full today.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "내 **일정**은 / 꽉 찼다 / 오늘.",
      "example_ko": "오늘 내 **일정**이 꽉 찼어."
    },
    {
      "id": "VD-ESS-009",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "dentist",
      "pos": "명사",
      "meaning": "치과 의사",
      "example": "I go to the dentist twice a year.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 간다 / **치과(치과 의사)**에 / 일 년에 두 번.",
      "example_ko": "나는 일 년에 두 번 **치과**에 가."
    },
    {
      "id": "VD-ESS-010",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "lawyer",
      "pos": "명사",
      "meaning": "변호사",
      "example": "Her mother is a famous lawyer.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀의 엄마는 / ~이다 / 유명한 **변호사**.",
      "example_ko": "그녀의 엄마는 유명한 **변호사**야."
    },
    {
      "id": "VD-ESS-011",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "engineer",
      "pos": "명사",
      "meaning": "기술자, 엔지니어",
      "example": "The engineer fixed the machine.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 **기술자**는 / 고쳤다 / 기계를.",
      "example_ko": "그 **기술자(엔지니어)**가 기계를 고쳤어."
    },
    {
      "id": "VD-ESS-012",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "officer",
      "pos": "명사",
      "meaning": "장교·경찰관·공무원",
      "example": "A police officer helped the child.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**경찰관(officer)**이 / 도왔다 / 그 아이를.",
      "example_ko": "**경찰관**이 그 아이를 도와줬어."
    },
    {
      "id": "VD-ESS-013",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "soldier",
      "pos": "명사",
      "meaning": "군인",
      "example": "The soldier is very brave.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 **군인**은 / 매우 / 용감하다.",
      "example_ko": "그 **군인**은 아주 용감해."
    },
    {
      "id": "VD-ESS-014",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "captain",
      "pos": "명사",
      "meaning": "(팀) 주장, 선장",
      "example": "He is the captain of our team.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그는 / ~이다 / **주장** / 우리 팀의.",
      "example_ko": "그는 우리 팀 **주장**이야."
    },
    {
      "id": "VD-ESS-015",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "guest",
      "pos": "명사",
      "meaning": "손님",
      "example": "We have a guest for dinner.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "우리는 있다 / **손님**이 / 저녁 식사에.",
      "example_ko": "우리 집에 저녁 **손님**이 와."
    },
    {
      "id": "VD-ESS-016",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "neighbor",
      "pos": "명사",
      "meaning": "이웃",
      "example": "My neighbor has a big dog.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "내 **이웃**은 / 키운다 / 큰 개를.",
      "example_ko": "내 **이웃**은 큰 개를 키워."
    },
    {
      "id": "VD-ESS-017",
      "unit": "필수",
      "theme": "사람·직업",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "citizen",
      "pos": "명사",
      "meaning": "시민",
      "example": "Every citizen can vote.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "모든 **시민**은 / 할 수 있다 / 투표를.",
      "example_ko": "모든 **시민**은 투표할 수 있어."
    },
    {
      "id": "VD-ESS-018",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "muscle",
      "pos": "명사",
      "meaning": "근육",
      "example": "Exercise makes your muscles strong.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "운동은 / 만든다 / 네 **근육**을 / 튼튼하게.",
      "example_ko": "운동은 네 **근육**을 튼튼하게 만들어."
    },
    {
      "id": "VD-ESS-019",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "stomach",
      "pos": "명사",
      "meaning": "위, 배",
      "example": "My stomach hurts after lunch.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "내 **배(위)**가 / 아프다 / 점심 후에.",
      "example_ko": "점심 먹고 나서 **배**가 아파."
    },
    {
      "id": "VD-ESS-020",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "throat",
      "pos": "명사",
      "meaning": "목구멍",
      "example": "I have a sore throat today.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 있다 / 아픈 **목(목구멍)**이 / 오늘.",
      "example_ko": "오늘 **목(목구멍)**이 아파."
    },
    {
      "id": "VD-ESS-021",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "tongue",
      "pos": "명사",
      "meaning": "혀",
      "example": "Don't burn your tongue on hot soup.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "데지 마 / 네 **혀**를 / 뜨거운 국에.",
      "example_ko": "뜨거운 국에 **혀** 데지 마."
    },
    {
      "id": "VD-ESS-022",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "toe",
      "pos": "명사",
      "meaning": "발가락",
      "example": "I hurt my toe on the door.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 다쳤다 / 내 **발가락**을 / 문에.",
      "example_ko": "문에 **발가락**을 찧었어."
    },
    {
      "id": "VD-ESS-023",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "cheek",
      "pos": "명사",
      "meaning": "뺨, 볼",
      "example": "Her cheeks turned red.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀의 **볼(뺨)**이 / 변했다 / 빨갛게.",
      "example_ko": "그녀의 **볼**이 빨개졌어."
    },
    {
      "id": "VD-ESS-024",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "chest",
      "pos": "명사",
      "meaning": "가슴",
      "example": "He felt a pain in his chest.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그는 느꼈다 / 통증을 / 그의 **가슴**에.",
      "example_ko": "그는 **가슴**에 통증을 느꼈어."
    },
    {
      "id": "VD-ESS-025",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "fever",
      "pos": "명사",
      "meaning": "열",
      "example": "She has a high fever.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 있다 / 높은 **열**이.",
      "example_ko": "그녀는 **열**이 높아."
    },
    {
      "id": "VD-ESS-026",
      "unit": "필수",
      "theme": "몸·건강",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "medicine",
      "pos": "명사",
      "meaning": "약",
      "example": "Take this medicine after meals.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "먹어 / 이 **약**을 / 식사 후에.",
      "example_ko": "식사 후에 이 **약**을 먹어."
    },
    {
      "id": "VD-ESS-027",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "garage",
      "pos": "명사",
      "meaning": "차고",
      "example": "Dad parks the car in the garage.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "아빠는 / 주차한다 / 차를 / **차고**에.",
      "example_ko": "아빠는 **차고**에 차를 세워."
    },
    {
      "id": "VD-ESS-028",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "gate",
      "pos": "명사",
      "meaning": "대문, 문",
      "example": "Please close the gate.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "닫아 주세요 / **문(대문)**을.",
      "example_ko": "**대문** 좀 닫아 줘."
    },
    {
      "id": "VD-ESS-029",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "ceiling",
      "pos": "명사",
      "meaning": "천장",
      "example": "There is a lamp on the ceiling.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "있다 / 전등이 / **천장**에.",
      "example_ko": "**천장**에 전등이 있어."
    },
    {
      "id": "VD-ESS-030",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "carpet",
      "pos": "명사",
      "meaning": "카펫, 양탄자",
      "example": "The cat sleeps on the carpet.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "고양이가 / 잔다 / **카펫** 위에서.",
      "example_ko": "고양이가 **카펫** 위에서 자."
    },
    {
      "id": "VD-ESS-031",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "envelope",
      "pos": "명사",
      "meaning": "봉투",
      "example": "She put the letter in an envelope.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 넣었다 / 편지를 / **봉투**에.",
      "example_ko": "그녀는 편지를 **봉투**에 넣었어."
    },
    {
      "id": "VD-ESS-032",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "calendar",
      "pos": "명사",
      "meaning": "달력",
      "example": "Mark the date on the calendar.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "표시해 / 날짜를 / **달력**에.",
      "example_ko": "**달력**에 날짜를 표시해."
    },
    {
      "id": "VD-ESS-033",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "towel",
      "pos": "명사",
      "meaning": "수건",
      "example": "Dry your hands with a towel.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "말려 / 네 손을 / **수건**으로.",
      "example_ko": "**수건**으로 손을 닦아."
    },
    {
      "id": "VD-ESS-034",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "blanket",
      "pos": "명사",
      "meaning": "담요",
      "example": "She covered the baby with a blanket.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 덮었다 / 아기를 / **담요**로.",
      "example_ko": "그녀는 아기를 **담요**로 덮어 줬어."
    },
    {
      "id": "VD-ESS-035",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "furniture",
      "pos": "명사",
      "meaning": "가구",
      "example": "We bought new furniture for our home.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "우리는 샀다 / 새 **가구**를 / 우리 집을 위해.",
      "example_ko": "우리는 집에 쓸 새 **가구**를 샀어."
    },
    {
      "id": "VD-ESS-036",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "mirror",
      "pos": "명사",
      "meaning": "거울",
      "example": "She looked at herself in the mirror.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 봤다 / 자신을 / **거울** 속에서.",
      "example_ko": "그녀는 **거울**로 자기 모습을 봤어."
    },
    {
      "id": "VD-ESS-037",
      "unit": "필수",
      "theme": "집·물건",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "tool",
      "pos": "명사",
      "meaning": "도구, 연장",
      "example": "A hammer is a useful tool.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "망치는 / ~이다 / 유용한 **도구**.",
      "example_ko": "망치는 유용한 **도구**야."
    },
    {
      "id": "VD-ESS-038",
      "unit": "필수",
      "theme": "옷",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "jeans",
      "pos": "명사",
      "meaning": "청바지",
      "example": "He wears blue jeans every day.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그는 입는다 / 파란 **청바지**를 / 매일.",
      "example_ko": "그는 매일 파란 **청바지**를 입어."
    },
    {
      "id": "VD-ESS-039",
      "unit": "필수",
      "theme": "옷",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "sweater",
      "pos": "명사",
      "meaning": "스웨터",
      "example": "Wear a warm sweater in winter.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "입어 / 따뜻한 **스웨터**를 / 겨울에.",
      "example_ko": "겨울엔 따뜻한 **스웨터**를 입어."
    },
    {
      "id": "VD-ESS-040",
      "unit": "필수",
      "theme": "옷",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "scarf",
      "pos": "명사",
      "meaning": "목도리, 스카프",
      "example": "She tied a scarf around her neck.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 둘렀다 / **목도리**를 / 목에.",
      "example_ko": "그녀는 목에 **목도리**를 둘렀어."
    },
    {
      "id": "VD-ESS-041",
      "unit": "필수",
      "theme": "옷",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "uniform",
      "pos": "명사",
      "meaning": "교복, 제복",
      "example": "We wear a school uniform.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "우리는 입는다 / 학교 **교복**을.",
      "example_ko": "우리는 학교 **교복**을 입어."
    },
    {
      "id": "VD-ESS-042",
      "unit": "필수",
      "theme": "음식",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "lemon",
      "pos": "명사",
      "meaning": "레몬",
      "example": "This drink tastes like lemon.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "이 음료는 / 맛이 난다 / **레몬** 같은.",
      "example_ko": "이 음료는 **레몬** 맛이 나."
    },
    {
      "id": "VD-ESS-043",
      "unit": "필수",
      "theme": "음식",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "pear",
      "pos": "명사",
      "meaning": "배(과일)",
      "example": "A pear is sweet and juicy.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**배**는 / ~이다 / 달고 즙이 많다.",
      "example_ko": "**배**는 달고 즙이 많아."
    },
    {
      "id": "VD-ESS-044",
      "unit": "필수",
      "theme": "음식",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "melon",
      "pos": "명사",
      "meaning": "멜론",
      "example": "We ate melon after dinner.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "우리는 먹었다 / **멜론**을 / 저녁 후에.",
      "example_ko": "우리는 저녁 먹고 **멜론**을 먹었어."
    },
    {
      "id": "VD-ESS-045",
      "unit": "필수",
      "theme": "음식",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "pepper",
      "pos": "명사",
      "meaning": "후추, 고추",
      "example": "Add some pepper to the soup.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "넣어 / 약간의 **후추**를 / 국에.",
      "example_ko": "국에 **후추** 좀 넣어."
    },
    {
      "id": "VD-ESS-046",
      "unit": "필수",
      "theme": "음식",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "mushroom",
      "pos": "명사",
      "meaning": "버섯",
      "example": "I don't like mushroom on pizza.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 안 좋아한다 / **버섯**을 / 피자 위의.",
      "example_ko": "나는 피자 위 **버섯**을 안 좋아해."
    },
    {
      "id": "VD-ESS-047",
      "unit": "필수",
      "theme": "음식",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "strawberry",
      "pos": "명사",
      "meaning": "딸기",
      "example": "Strawberry jam is my favorite.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**딸기** 잼은 / ~이다 / 내가 제일 좋아하는 것.",
      "example_ko": "**딸기** 잼이 내가 제일 좋아하는 거야."
    },
    {
      "id": "VD-ESS-048",
      "unit": "필수",
      "theme": "음식",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "recipe",
      "pos": "명사",
      "meaning": "요리법, 레시피",
      "example": "This recipe is easy to follow.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "이 **요리법**은 / ~이다 / 따라 하기 쉬운.",
      "example_ko": "이 **요리법(레시피)**은 따라 하기 쉬워."
    },
    {
      "id": "VD-ESS-049",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "dolphin",
      "pos": "명사",
      "meaning": "돌고래",
      "example": "Dolphins are very smart animals.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**돌고래**는 / ~이다 / 아주 똑똑한 동물.",
      "example_ko": "**돌고래**는 아주 똑똑한 동물이야."
    },
    {
      "id": "VD-ESS-050",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "whale",
      "pos": "명사",
      "meaning": "고래",
      "example": "The whale is the biggest animal.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**고래**는 / ~이다 / 가장 큰 동물.",
      "example_ko": "**고래**는 가장 큰 동물이야."
    },
    {
      "id": "VD-ESS-051",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "zebra",
      "pos": "명사",
      "meaning": "얼룩말",
      "example": "A zebra has black and white stripes.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**얼룩말**은 / 가진다 / 검고 흰 줄무늬를.",
      "example_ko": "**얼룩말**은 검은색과 흰색 줄무늬가 있어."
    },
    {
      "id": "VD-ESS-052",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "giraffe",
      "pos": "명사",
      "meaning": "기린",
      "example": "The giraffe has a very long neck.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**기린**은 / 가진다 / 아주 긴 목을.",
      "example_ko": "**기린**은 목이 아주 길어."
    },
    {
      "id": "VD-ESS-053",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "snake",
      "pos": "명사",
      "meaning": "뱀",
      "example": "A snake moved through the grass.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**뱀**이 / 움직였다 / 풀 사이로.",
      "example_ko": "**뱀**이 풀 사이로 지나갔어."
    },
    {
      "id": "VD-ESS-054",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "sheep",
      "pos": "명사",
      "meaning": "양",
      "example": "The sheep are eating grass.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 **양**들이 / 먹고 있다 / 풀을.",
      "example_ko": "**양**들이 풀을 먹고 있어."
    },
    {
      "id": "VD-ESS-055",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "ant",
      "pos": "명사",
      "meaning": "개미",
      "example": "An ant is small but strong.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**개미**는 / ~이다 / 작지만 힘세다.",
      "example_ko": "**개미**는 작지만 힘이 세."
    },
    {
      "id": "VD-ESS-056",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "leaf",
      "pos": "명사",
      "meaning": "(나뭇)잎",
      "example": "A yellow leaf fell from the tree.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "노란 **잎**이 / 떨어졌다 / 나무에서.",
      "example_ko": "노란 **잎**이 나무에서 떨어졌어."
    },
    {
      "id": "VD-ESS-057",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "valley",
      "pos": "명사",
      "meaning": "계곡, 골짜기",
      "example": "A river runs through the valley.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "강이 / 흐른다 / **계곡**을 통과해.",
      "example_ko": "강이 **계곡** 사이로 흘러."
    },
    {
      "id": "VD-ESS-058",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "planet",
      "pos": "명사",
      "meaning": "행성",
      "example": "Earth is our home planet.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "지구는 / ~이다 / 우리의 고향 **행성**.",
      "example_ko": "지구는 우리 고향 **행성**이야."
    },
    {
      "id": "VD-ESS-059",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "rainbow",
      "pos": "명사",
      "meaning": "무지개",
      "example": "A rainbow appeared after the rain.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**무지개**가 / 나타났다 / 비 온 뒤에.",
      "example_ko": "비 온 뒤에 **무지개**가 떴어."
    },
    {
      "id": "VD-ESS-060",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "storm",
      "pos": "명사",
      "meaning": "폭풍",
      "example": "The storm broke many trees.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 **폭풍**은 / 부러뜨렸다 / 많은 나무를.",
      "example_ko": "그 **폭풍**이 나무를 많이 부러뜨렸어."
    },
    {
      "id": "VD-ESS-061",
      "unit": "필수",
      "theme": "동물·자연",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "flood",
      "pos": "명사",
      "meaning": "홍수",
      "example": "The flood covered the whole road.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 **홍수**가 / 덮었다 / 온 도로를.",
      "example_ko": "**홍수**가 도로를 다 덮어 버렸어."
    },
    {
      "id": "VD-ESS-062",
      "unit": "필수",
      "theme": "장소",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "airport",
      "pos": "명사",
      "meaning": "공항",
      "example": "We arrived at the airport early.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "우리는 도착했다 / **공항**에 / 일찍.",
      "example_ko": "우리는 **공항**에 일찍 도착했어."
    },
    {
      "id": "VD-ESS-063",
      "unit": "필수",
      "theme": "장소",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "palace",
      "pos": "명사",
      "meaning": "궁전",
      "example": "The king lived in a huge palace.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 왕은 / 살았다 / 거대한 **궁전**에서.",
      "example_ko": "그 왕은 거대한 **궁전**에 살았어."
    },
    {
      "id": "VD-ESS-064",
      "unit": "필수",
      "theme": "장소",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "castle",
      "pos": "명사",
      "meaning": "성",
      "example": "The old castle is on a hill.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 오래된 **성**은 / 있다 / 언덕 위에.",
      "example_ko": "그 오래된 **성**은 언덕 위에 있어."
    },
    {
      "id": "VD-ESS-065",
      "unit": "필수",
      "theme": "장소",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "highway",
      "pos": "명사",
      "meaning": "고속도로",
      "example": "Cars move fast on the highway.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "차들은 / 달린다 / 빠르게 / **고속도로**에서.",
      "example_ko": "**고속도로**에서 차들이 빠르게 달려."
    },
    {
      "id": "VD-ESS-066",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "polite",
      "pos": "형용사",
      "meaning": "예의 바른",
      "example": "She is always polite to elders.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 / 항상 / **예의 바르다** / 어른들에게.",
      "example_ko": "그녀는 어른들에게 늘 **예의 발라**."
    },
    {
      "id": "VD-ESS-067",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "silly",
      "pos": "형용사",
      "meaning": "어리석은, 바보 같은",
      "example": "That was a silly mistake.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그것은 / ~였다 / **바보 같은** 실수.",
      "example_ko": "그건 **바보 같은** 실수였어."
    },
    {
      "id": "VD-ESS-068",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "cruel",
      "pos": "형용사",
      "meaning": "잔인한",
      "example": "It is cruel to hurt animals.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그것은 / ~이다 / **잔인한** / 동물을 해치는 것은.",
      "example_ko": "동물을 해치는 건 **잔인해**."
    },
    {
      "id": "VD-ESS-069",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "rude",
      "pos": "형용사",
      "meaning": "무례한",
      "example": "It is rude to interrupt others.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그것은 / ~이다 / **무례한** / 남을 방해하는 것은.",
      "example_ko": "남의 말을 끊는 건 **무례해**."
    },
    {
      "id": "VD-ESS-070",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "wise",
      "pos": "형용사",
      "meaning": "현명한, 지혜로운",
      "example": "My grandmother is very wise.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "우리 할머니는 / 매우 / **현명하다**.",
      "example_ko": "우리 할머니는 아주 **현명하셔**."
    },
    {
      "id": "VD-ESS-071",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "calm",
      "pos": "형용사",
      "meaning": "차분한, 침착한",
      "example": "Stay calm during the test.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "유지해 / **침착함**을 / 시험 중에.",
      "example_ko": "시험 볼 때 **침착하게** 있어."
    },
    {
      "id": "VD-ESS-072",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "gentle",
      "pos": "형용사",
      "meaning": "온화한, 부드러운",
      "example": "Be gentle with the puppy.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "대해 / **부드럽게** / 강아지를.",
      "example_ko": "강아지를 **부드럽게(살살)** 대해."
    },
    {
      "id": "VD-ESS-073",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "huge",
      "pos": "형용사",
      "meaning": "거대한",
      "example": "They live in a huge house.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그들은 산다 / **거대한** 집에서.",
      "example_ko": "그들은 **엄청 큰(거대한)** 집에 살아."
    },
    {
      "id": "VD-ESS-074",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "empty",
      "pos": "형용사",
      "meaning": "텅 빈",
      "example": "The box was empty inside.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 상자는 / ~였다 / 안이 **텅 빈**.",
      "example_ko": "그 상자는 안이 **텅 비어** 있었어."
    },
    {
      "id": "VD-ESS-075",
      "unit": "필수",
      "theme": "성격·형용사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "smooth",
      "pos": "형용사",
      "meaning": "매끄러운",
      "example": "The stone felt smooth and cool.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 돌은 / 느껴졌다 / **매끄럽고** 시원하게.",
      "example_ko": "그 돌은 **매끈하고** 시원했어."
    },
    {
      "id": "VD-ESS-076",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "lend",
      "pos": "동사",
      "meaning": "빌려주다",
      "example": "Can you lend me your pen?",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**빌려줄래** / 나에게 / 네 펜을?",
      "example_ko": "네 펜 좀 **빌려줄래**?"
    },
    {
      "id": "VD-ESS-077",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "hire",
      "pos": "동사",
      "meaning": "고용하다",
      "example": "The shop will hire two workers.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 가게는 / **고용할** 것이다 / 두 명의 일꾼을.",
      "example_ko": "그 가게는 일꾼 두 명을 **고용할** 거야."
    },
    {
      "id": "VD-ESS-078",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "deliver",
      "pos": "동사",
      "meaning": "배달하다",
      "example": "They deliver pizza to our house.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그들은 / **배달한다** / 피자를 / 우리 집으로.",
      "example_ko": "그들은 우리 집에 피자를 **배달해**."
    },
    {
      "id": "VD-ESS-079",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "repair",
      "pos": "동사",
      "meaning": "수리하다, 고치다",
      "example": "He can repair a broken bike.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그는 / **수리할** 수 있다 / 고장 난 자전거를.",
      "example_ko": "그는 고장 난 자전거를 **고칠(수리할)** 수 있어."
    },
    {
      "id": "VD-ESS-080",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "fold",
      "pos": "동사",
      "meaning": "접다",
      "example": "Please fold your clothes neatly.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**접어** 줘 / 네 옷을 / 단정하게.",
      "example_ko": "옷을 단정하게 **접어**."
    },
    {
      "id": "VD-ESS-081",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "dig",
      "pos": "동사",
      "meaning": "파다",
      "example": "The dog likes to dig holes.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 개는 / 좋아한다 / **파는** 것을 / 구멍을.",
      "example_ko": "그 개는 구멍 **파는** 걸 좋아해."
    },
    {
      "id": "VD-ESS-082",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "bite",
      "pos": "동사",
      "meaning": "물다",
      "example": "That dog may bite strangers.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 개는 / **물** 수도 있다 / 낯선 사람을.",
      "example_ko": "그 개는 낯선 사람을 **물** 수도 있어."
    },
    {
      "id": "VD-ESS-083",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "grab",
      "pos": "동사",
      "meaning": "움켜쥐다, 붙잡다",
      "example": "Don't grab other people's things.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**붙잡지(움켜쥐지)** 마 / 다른 사람의 물건을.",
      "example_ko": "남의 물건을 함부로 **붙잡지** 마."
    },
    {
      "id": "VD-ESS-084",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "chase",
      "pos": "동사",
      "meaning": "뒤쫓다",
      "example": "Cats love to chase mice.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "고양이는 / 좋아한다 / **뒤쫓는** 것을 / 쥐를.",
      "example_ko": "고양이는 쥐 **쫓는** 걸 좋아해."
    },
    {
      "id": "VD-ESS-085",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "freeze",
      "pos": "동사",
      "meaning": "얼다, 얼리다",
      "example": "Water will freeze in cold weather.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "물은 / **얼** 것이다 / 추운 날씨에.",
      "example_ko": "물은 추우면 **얼어**."
    },
    {
      "id": "VD-ESS-086",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "pour",
      "pos": "동사",
      "meaning": "붓다, 따르다",
      "example": "Pour some water into the cup.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**부어** / 약간의 물을 / 컵에.",
      "example_ko": "컵에 물 좀 **부어(따라)**."
    },
    {
      "id": "VD-ESS-087",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "scream",
      "pos": "동사",
      "meaning": "비명을 지르다",
      "example": "Don't scream in the classroom.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**소리 지르지** 마 / 교실에서.",
      "example_ko": "교실에서 **소리 지르지(비명 지르지)** 마."
    },
    {
      "id": "VD-ESS-088",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "greet",
      "pos": "동사",
      "meaning": "인사하다, 맞이하다",
      "example": "She greets everyone with a smile.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 / **인사한다** / 모두에게 / 미소로.",
      "example_ko": "그녀는 모두에게 웃으며 **인사해**."
    },
    {
      "id": "VD-ESS-089",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "warn",
      "pos": "동사",
      "meaning": "경고하다",
      "example": "I warned him about the danger.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 / **경고했다** / 그에게 / 위험에 대해.",
      "example_ko": "나는 그에게 위험을 **경고했어**."
    },
    {
      "id": "VD-ESS-090",
      "unit": "필수",
      "theme": "동작 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "escape",
      "pos": "동사",
      "meaning": "탈출하다, 도망치다",
      "example": "The bird escaped from its cage.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그 새는 / **탈출했다** / 새장에서.",
      "example_ko": "그 새가 새장에서 **도망쳤어(탈출했어)**."
    },
    {
      "id": "VD-ESS-091",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "imagine",
      "pos": "동사",
      "meaning": "상상하다",
      "example": "Imagine a world without phones.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**상상해 봐** / 세상을 / 전화기 없는.",
      "example_ko": "전화기 없는 세상을 **상상해 봐**."
    },
    {
      "id": "VD-ESS-092",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "improve",
      "pos": "동사",
      "meaning": "향상시키다, 나아지다",
      "example": "Reading can improve your writing.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "독서는 / **향상시킬** 수 있다 / 네 글쓰기를.",
      "example_ko": "책 읽기는 네 글쓰기를 **좋아지게(향상시킬)** 해."
    },
    {
      "id": "VD-ESS-093",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "increase",
      "pos": "동사",
      "meaning": "증가하다, 늘리다",
      "example": "Prices increase every year.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "가격은 / **오른다(증가한다)** / 매년.",
      "example_ko": "가격이 해마다 **올라(증가해)**."
    },
    {
      "id": "VD-ESS-094",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "promise",
      "pos": "동사",
      "meaning": "약속하다",
      "example": "I promise to be on time.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 / **약속한다** / 제시간에 오기로.",
      "example_ko": "나 제시간에 올 거라고 **약속해**."
    },
    {
      "id": "VD-ESS-095",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "repeat",
      "pos": "동사",
      "meaning": "반복하다",
      "example": "Please repeat the question.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "**반복해** 주세요 / 질문을.",
      "example_ko": "질문을 다시 한 번 **말해(반복해)** 줘."
    },
    {
      "id": "VD-ESS-096",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "reply",
      "pos": "동사",
      "meaning": "대답하다, 답장하다",
      "example": "She didn't reply to my message.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그녀는 / **답하지** 않았다 / 내 메시지에.",
      "example_ko": "그녀는 내 메시지에 **답(답장)하지** 않았어."
    },
    {
      "id": "VD-ESS-097",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "notice",
      "pos": "동사",
      "meaning": "알아채다",
      "example": "I didn't notice the mistake.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 / **알아채지** 못했다 / 그 실수를.",
      "example_ko": "나는 그 실수를 **못 알아챘어**."
    },
    {
      "id": "VD-ESS-098",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "offer",
      "pos": "동사",
      "meaning": "제안하다, 권하다",
      "example": "They offered me a cup of tea.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "그들은 / **권했다(제안했다)** / 나에게 / 차 한 잔을.",
      "example_ko": "그들은 나에게 차 한 잔을 **권했어**."
    },
    {
      "id": "VD-ESS-099",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "suggest",
      "pos": "동사",
      "meaning": "제안하다",
      "example": "I suggest a short break.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 / **제안한다** / 짧은 휴식을.",
      "example_ko": "나는 잠깐 쉬자고 **제안해**."
    },
    {
      "id": "VD-ESS-100",
      "unit": "필수",
      "theme": "자주 쓰는 동사",
      "source": "교육부 2022 개정 기본어휘 **표(중·고 공통)",
      "level": "**",
      "word": "recommend",
      "pos": "동사",
      "meaning": "추천하다",
      "example": "I recommend this book to you.",
      "example_source": "기본어휘 예문(자체 제작·중2 수준)",
      "example_ko_chunk": "나는 / **추천한다** / 이 책을 / 너에게.",
      "example_ko": "나는 너에게 이 책을 **추천해**."
    }
  ]
});
