__loadLesson({
  "lesson": 7,
  "title": "Lesson 7: Natural Wonders",
  "version": "1.0",
  "build_date": "2026-07-12",
  "build_note": "v1.0 — 2학기 단어트랙 신규: 천재교육 Word List p.184~186 전수(이미지 판독 검증) + example은 교과서 본문/스크립트 채취. unit 필드=교과서 단원 태깅",
  "core_sentences": [],
  "grammar_rules": [],
  "questions": [],
  "vocab_drill": [
    {
      "id": "VD-L7-001",
      "unit": "L7",
      "word": "baobab tree",
      "pos": "명사",
      "meaning": "바오밥 나무",
      "example": "You can see rhinos which are sleeping under baobab trees.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "너는 / 볼 수 있다 / 코뿔소들을 / 자고 있는 / **바오밥 나무** 아래에서.",
      "example_ko": "**바오밥 나무** 아래에서 자는 코뿔소를 볼 수 있어. (관계대명사 which)",
      "inflections": [
        "baobab trees"
      ]
    },
    {
      "id": "VD-L7-002",
      "unit": "L7",
      "word": "beauty",
      "pos": "명사",
      "meaning": "아름다움",
      "example": "They let people enjoy the beauty of nature.",
      "example_source": "본문 p.123",
      "example_ko_chunk": "그것들은 / 하게 한다 / 사람들이 / 즐기게 / 자연의 **아름다움**을.",
      "example_ko": "국립 공원은 사람들이 자연의 **아름다움**을 즐기게 해 줘. (let+목적어+동사원형)"
    },
    {
      "id": "VD-L7-003",
      "unit": "L7",
      "word": "book",
      "pos": "동사·명사",
      "meaning": "예약하다 / 책",
      "example": "They should book to enter the park.",
      "example_source": "본문 p.125",
      "example_ko_chunk": "그들은 / **예약해야** 한다 / 들어가려면 / 공원에.",
      "example_ko": "공원에 들어가려면 **예약해야** 해."
    },
    {
      "id": "VD-L7-004",
      "unit": "L7",
      "word": "bright",
      "pos": "형용사",
      "meaning": "(색이) 밝은",
      "example": "They're famous for their bright colors like pink, white, and red.",
      "example_source": "스크립트 p.170 (Enjoy the Clip)",
      "example_ko_chunk": "그것들은 / 유명하다 / **밝은** 색으로 / 분홍, 하양, 빨강 같은.",
      "example_ko": "그 꽃들은 분홍·하양·빨강 같은 **밝은** 색으로 유명해."
    },
    {
      "id": "VD-L7-005",
      "unit": "L7",
      "word": "buffalo",
      "pos": "명사",
      "meaning": "버팔로",
      "example": "They are lions, leopards, elephants, rhinos, and buffaloes.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "그것들은 / 사자, 표범, 코끼리, / 코뿔소, 그리고 **버팔로**이다.",
      "example_ko": "Big Five는 사자, 표범, 코끼리, 코뿔소, **버팔로**야."
    },
    {
      "id": "VD-L7-006",
      "unit": "L7",
      "word": "coach",
      "pos": "명사",
      "meaning": "(스포츠 팀의) 코치",
      "example": "The coach let the players take a break.",
      "example_source": "본문 p.134 (Review)",
      "example_ko_chunk": "**코치**는 / 하게 했다 / 선수들이 / 쉬게.",
      "example_ko": "**코치**는 선수들을 쉬게 해 줬어. (let+목적어+동사원형)"
    },
    {
      "id": "VD-L7-007",
      "unit": "L7",
      "word": "control",
      "pos": "동사",
      "meaning": "통제하다, 규제하다",
      "example": "It controls the number of visitors.",
      "example_source": "본문 p.125",
      "example_ko_chunk": "그것은 / **통제한다** / 방문객의 수를.",
      "example_ko": "공원은 방문객 수를 **통제해**."
    },
    {
      "id": "VD-L7-008",
      "unit": "L7",
      "word": "dynamic",
      "pos": "형용사",
      "meaning": "역동적인",
      "example": "It is famous for its dynamic weather.",
      "example_source": "본문 p.124",
      "example_ko_chunk": "그곳은 / 유명하다 / **역동적인** 날씨로.",
      "example_ko": "그곳은 **역동적인**(변화무쌍한) 날씨로 유명해."
    },
    {
      "id": "VD-L7-009",
      "unit": "L7",
      "word": "effort",
      "pos": "명사",
      "meaning": "노력",
      "example": "The park is making efforts to preserve its natural beauty.",
      "example_source": "본문 p.124",
      "example_ko_chunk": "공원은 / 하고 있다 / **노력**을 / 보존하려는 / 자연의 아름다움을.",
      "example_ko": "공원은 자연의 아름다움을 지키려고 **노력**하고 있어."
    },
    {
      "id": "VD-L7-010",
      "unit": "L7",
      "word": "environment",
      "pos": "명사",
      "meaning": "환경",
      "example": "It monitors the environment and makes visitors take their trash with them.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "그것은 / 관찰한다 / **환경**을 / 그리고 하게 만든다 / 방문객들이 / 가져가게 / 쓰레기를.",
      "example_ko": "공원은 **환경**을 살피고, 방문객이 쓰레기를 가져가게 해. (make+목적어+동사원형)"
    },
    {
      "id": "VD-L7-011",
      "unit": "L7",
      "word": "explore",
      "pos": "동사",
      "meaning": "탐험하다",
      "example": "Visitors can ride boats to explore the islands and enjoy many hiking trails.",
      "example_source": "본문 p.124",
      "example_ko_chunk": "방문객들은 / 탈 수 있다 / 배를 / **탐험하기** 위해 / 섬들을.",
      "example_ko": "방문객들은 배를 타고 섬을 **탐험할** 수 있어."
    },
    {
      "id": "VD-L7-012",
      "unit": "L7",
      "word": "feature",
      "pos": "명사",
      "meaning": "특징",
      "example": "What are the features of this park?",
      "example_source": "본문 p.132 응용",
      "example_ko_chunk": "무엇인가 / **특징**들은 / 이 공원의?",
      "example_ko": "이 공원의 **특징**은 뭐야?"
    },
    {
      "id": "VD-L7-013",
      "unit": "L7",
      "word": "flying squirrel",
      "pos": "명사",
      "meaning": "날다람쥐",
      "example": "Isn't that a flying squirrel?",
      "example_source": "본문 p.118 (Listen & Talk 스크립트)",
      "example_ko_chunk": "저것은 / **날다람쥐** 아니야?",
      "example_ko": "저거 **날다람쥐** 아니야?"
    },
    {
      "id": "VD-L7-014",
      "unit": "L7",
      "word": "glacier",
      "pos": "명사",
      "meaning": "빙하",
      "example": "Grey Glacier, one of the most wonderful glaciers in Chile, welcomes you in the park.",
      "example_source": "본문 p.124",
      "example_ko_chunk": "그레이 **빙하**가, / 하나인 / 칠레에서 가장 멋진 **빙하** 중, / 너를 맞아 준다 / 공원에서.",
      "example_ko": "칠레에서 가장 멋진 **빙하** 중 하나인 그레이 **빙하**가 공원에서 너를 맞아 줘."
    },
    {
      "id": "VD-L7-015",
      "unit": "L7",
      "word": "helicopter",
      "pos": "명사",
      "meaning": "헬리콥터",
      "example": "These days, drones and helicopters are used to monitor hunting activities.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "요즘, / 드론과 **헬리콥터**가 / 사용된다 / 감시하기 위해 / 사냥 활동을.",
      "example_ko": "요즘은 드론과 **헬리콥터**로 사냥 활동을 감시해."
    },
    {
      "id": "VD-L7-016",
      "unit": "L7",
      "word": "hiking",
      "pos": "명사",
      "meaning": "하이킹, 도보 여행",
      "example": "Only some park trails are open to visitors for hiking.",
      "example_source": "본문 p.125",
      "example_ko_chunk": "오직 일부 / 공원 길들만 / 열려 있다 / 방문객들에게 / **하이킹**을 위해.",
      "example_ko": "일부 공원 길만 **하이킹**용으로 방문객에게 열려 있어."
    },
    {
      "id": "VD-L7-017",
      "unit": "L7",
      "word": "hunting",
      "pos": "명사",
      "meaning": "사냥",
      "example": "The Big Five are in danger because of too much hunting.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "Big Five는 / 위험에 처해 있다 / 너무 많은 **사냥** 때문에.",
      "example_ko": "Big Five는 지나친 **사냥** 때문에 위험에 처해 있어."
    },
    {
      "id": "VD-L7-018",
      "unit": "L7",
      "word": "icy",
      "pos": "형용사",
      "meaning": "얼음에 뒤덮인",
      "example": "It is exciting to walk on the glacier and enjoy the icy view.",
      "example_source": "본문 p.124",
      "example_ko_chunk": "신난다 / 걷는 것은 / 빙하 위를 / 그리고 즐기는 것은 / **얼음에 뒤덮인** 풍경을.",
      "example_ko": "빙하 위를 걸으며 **얼음** 풍경을 즐기는 건 신나. (It ~ to부정사)"
    },
    {
      "id": "VD-L7-019",
      "unit": "L7",
      "word": "illegal",
      "pos": "형용사",
      "meaning": "불법적인",
      "example": "Volunteers monitor signs of illegal hunting activities and remove animal traps.",
      "example_source": "본문 p.127",
      "example_ko_chunk": "자원봉사자들은 / 감시한다 / **불법** 사냥 활동의 흔적을 / 그리고 없앤다 / 동물 덫을.",
      "example_ko": "자원봉사자들은 **불법** 사냥의 흔적을 감시하고 동물 덫을 없애."
    },
    {
      "id": "VD-L7-020",
      "unit": "L7",
      "word": "in danger",
      "pos": "숙어",
      "meaning": "위험에 처한",
      "example": "The Big Five are in danger because of too much hunting.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "Big Five는 / **위험에 처해** 있다 / 너무 많은 사냥 때문에.",
      "example_ko": "Big Five는 지나친 사냥 때문에 **위험에 처해** 있어."
    },
    {
      "id": "VD-L7-021",
      "unit": "L7",
      "word": "leopard",
      "pos": "명사",
      "meaning": "표범",
      "example": "They are lions, leopards, elephants, rhinos, and buffaloes.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "그것들은 / 사자, **표범**, 코끼리, / 코뿔소, 그리고 버팔로이다.",
      "example_ko": "Big Five는 사자, **표범**, 코끼리, 코뿔소, 버팔로야."
    },
    {
      "id": "VD-L7-022",
      "unit": "L7",
      "word": "location",
      "pos": "명사",
      "meaning": "위치",
      "example": "Write the location of the park in your report.",
      "example_source": "본문 p.132 응용",
      "example_ko_chunk": "써라 / **위치**를 / 공원의 / 네 보고서에.",
      "example_ko": "보고서에 공원의 **위치**를 써 봐."
    },
    {
      "id": "VD-L7-023",
      "unit": "L7",
      "word": "monitor",
      "pos": "동사",
      "meaning": "감시하다, 관찰하다",
      "example": "These days, drones and helicopters are used to monitor hunting activities.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "요즘, / 드론과 헬리콥터가 / 사용된다 / **감시하기** 위해 / 사냥 활동을.",
      "example_ko": "요즘은 사냥 활동을 **감시하려고** 드론과 헬리콥터가 쓰여."
    },
    {
      "id": "VD-L7-024",
      "unit": "L7",
      "word": "national park",
      "pos": "명사",
      "meaning": "국립 공원",
      "example": "Have you heard about a national park passport?",
      "example_source": "본문 p.118 (Listen & Talk)",
      "example_ko_chunk": "들어 봤니 / **국립 공원** 여권에 대해?",
      "example_ko": "**국립 공원** 여권에 대해 들어 봤어?"
    },
    {
      "id": "VD-L7-025",
      "unit": "L7",
      "word": "passport",
      "pos": "명사",
      "meaning": "여권",
      "example": "If you collect all the stamps in your park passport, you can get a gift.",
      "example_source": "본문 p.118 (Listen & Talk 스크립트)",
      "example_ko_chunk": "만약 네가 모으면 / 모든 도장을 / 네 공원 **여권**에, / 너는 받을 수 있다 / 선물을.",
      "example_ko": "공원 **여권**에 도장을 다 모으면 선물을 받을 수 있어."
    },
    {
      "id": "VD-L7-026",
      "unit": "L7",
      "word": "possible",
      "pos": "형용사",
      "meaning": "가능한",
      "example": "It is possible to see wild animals in the park.",
      "example_source": "본문 p.131 응용 (Play with Language)",
      "example_ko_chunk": "**가능하다** / 보는 것이 / 야생 동물을 / 공원에서.",
      "example_ko": "공원에서 야생 동물을 보는 게 **가능해**. (It ~ to부정사)"
    },
    {
      "id": "VD-L7-027",
      "unit": "L7",
      "word": "present",
      "pos": "명사",
      "meaning": "현재, 선물",
      "example": "National parks preserve the Earth's past, present, and future.",
      "example_source": "본문 p.127",
      "example_ko_chunk": "국립 공원은 / 보존한다 / 지구의 과거, / **현재**, 그리고 미래를.",
      "example_ko": "국립 공원은 지구의 과거·**현재**·미래를 지켜 줘."
    },
    {
      "id": "VD-L7-028",
      "unit": "L7",
      "word": "preserve",
      "pos": "동사",
      "meaning": "보존하다, 보호하다",
      "example": "National parks are special places for preserving nature.",
      "example_source": "본문 p.123",
      "example_ko_chunk": "국립 공원은 / 특별한 장소이다 / **보존하기** 위한 / 자연을.",
      "example_ko": "국립 공원은 자연을 **보존하기** 위한 특별한 곳이야."
    },
    {
      "id": "VD-L7-029",
      "unit": "L7",
      "word": "product",
      "pos": "명사",
      "meaning": "제품, 상품",
      "example": "The hotels in the park only use eco-friendly products.",
      "example_source": "본문 p.125",
      "example_ko_chunk": "호텔들은 / 공원 안의 / 오직 사용한다 / 친환경 **제품**만.",
      "example_ko": "공원 안 호텔들은 친환경 **제품**만 써."
    },
    {
      "id": "VD-L7-030",
      "unit": "L7",
      "word": "rhino",
      "pos": "명사",
      "meaning": "코뿔소",
      "example": "You can see rhinos which are sleeping under baobab trees.",
      "example_source": "본문 p.126",
      "example_ko_chunk": "너는 / 볼 수 있다 / **코뿔소**들을 / 자고 있는 / 바오밥 나무 아래에서.",
      "example_ko": "바오밥 나무 아래서 자는 **코뿔소**를 볼 수 있어."
    },
    {
      "id": "VD-L7-031",
      "unit": "L7",
      "word": "run",
      "pos": "동사",
      "meaning": "운영하다, 달리다",
      "example": "The park runs many nature volunteer programs.",
      "example_source": "본문 p.127",
      "example_ko_chunk": "공원은 / **운영한다** / 많은 자연 자원봉사 프로그램을.",
      "example_ko": "공원은 많은 자연 자원봉사 프로그램을 **운영해**."
    },
    {
      "id": "VD-L7-032",
      "unit": "L7",
      "word": "single",
      "pos": "형용사",
      "meaning": "하나의",
      "example": "It can be sunny, rainy, or snowy in a single day!",
      "example_source": "본문 p.124",
      "example_ko_chunk": "맑고, 비 오고, 눈 올 수 있다 / **하루(단 하나의 날)** 안에!",
      "example_ko": "**단 하루** 안에 맑았다가 비 왔다가 눈이 올 수도 있어!"
    },
    {
      "id": "VD-L7-033",
      "unit": "L7",
      "word": "species",
      "pos": "명사",
      "meaning": "(생물 분류상의) 종",
      "example": "They keep many animal and plant species safe.",
      "example_source": "본문 p.123",
      "example_ko_chunk": "그것들은 / 유지한다 / 많은 동물과 식물 **종**을 / 안전하게.",
      "example_ko": "국립 공원은 많은 동식물 **종**을 안전하게 지켜. (keep+목적어+형용사)"
    },
    {
      "id": "VD-L7-034",
      "unit": "L7",
      "word": "stamp",
      "pos": "명사",
      "meaning": "도장",
      "example": "You can get a stamp at the visitor center.",
      "example_source": "본문 p.118 (Listen & Talk 스크립트)",
      "example_ko_chunk": "너는 / 받을 수 있다 / **도장**을 / 방문객 센터에서.",
      "example_ko": "방문객 센터에서 **도장**을 받을 수 있어."
    },
    {
      "id": "VD-L7-035",
      "unit": "L7",
      "word": "take a look at",
      "pos": "숙어",
      "meaning": "~을/를 살펴보다",
      "example": "Let's take a look at two famous national parks in South America and Africa.",
      "example_source": "본문 p.123",
      "example_ko_chunk": "**살펴보자** / 두 개의 유명한 국립 공원을 / 남아메리카와 아프리카에 있는.",
      "example_ko": "남아메리카와 아프리카의 유명 국립 공원 두 곳을 **살펴보자**."
    },
    {
      "id": "VD-L7-036",
      "unit": "L7",
      "word": "thunderstorm",
      "pos": "명사",
      "meaning": "뇌우(천둥과 번개를 동반한 비)",
      "example": "It is easy to see thunderstorms in the summer.",
      "example_source": "본문 p.132 (Write)",
      "example_ko_chunk": "쉽다 / 보는 것은 / **뇌우**를 / 여름에.",
      "example_ko": "여름엔 **뇌우**(천둥·번개 비)를 보기 쉬워. (It ~ to부정사)"
    },
    {
      "id": "VD-L7-037",
      "unit": "L7",
      "word": "trail",
      "pos": "명사",
      "meaning": "코스, 산길",
      "example": "Only some park trails are open to visitors for hiking.",
      "example_source": "본문 p.125",
      "example_ko_chunk": "오직 일부 / 공원 **길(코스)**들만 / 열려 있다 / 방문객들에게 / 하이킹을 위해.",
      "example_ko": "일부 공원 **산길**만 하이킹용으로 열려 있어."
    },
    {
      "id": "VD-L7-038",
      "unit": "L7",
      "word": "trap",
      "pos": "명사",
      "meaning": "덫",
      "example": "Volunteers monitor signs of illegal hunting activities and remove animal traps.",
      "example_source": "본문 p.127",
      "example_ko_chunk": "자원봉사자들은 / 감시한다 / 불법 사냥의 흔적을 / 그리고 없앤다 / 동물 **덫**을.",
      "example_ko": "자원봉사자들은 불법 사냥 흔적을 감시하고 동물 **덫**을 없애."
    },
    {
      "id": "VD-L7-039",
      "unit": "L7",
      "word": "visitor",
      "pos": "명사",
      "meaning": "방문객",
      "example": "Visitors can ride boats to explore the islands.",
      "example_source": "본문 p.124 일부",
      "example_ko_chunk": "**방문객**들은 / 탈 수 있다 / 배를 / 탐험하기 위해 / 섬들을.",
      "example_ko": "**방문객**들은 배를 타고 섬을 탐험할 수 있어."
    },
    {
      "id": "VD-L7-040",
      "unit": "L7",
      "word": "wisdom",
      "pos": "명사",
      "meaning": "지혜",
      "example": "Asters stand for love and wisdom.",
      "example_source": "본문 p.120",
      "example_ko_chunk": "애스터(과꽃)는 / 상징한다 / 사랑과 **지혜**를.",
      "example_ko": "애스터(과꽃)는 사랑과 **지혜**를 상징해."
    },
    {
      "id": "VD-L7-041",
      "unit": "L7",
      "word": "wonderland",
      "pos": "명사",
      "meaning": "아주 멋진 곳",
      "example": "Wild wonderlands let people enjoy the beauty of nature.",
      "example_source": "본문 p.123 응용",
      "example_ko_chunk": "야생의 **아주 멋진 곳**들은 / 하게 한다 / 사람들이 / 즐기게 / 자연의 아름다움을.",
      "example_ko": "야생의 **원더랜드(아주 멋진 곳)**는 사람들이 자연의 아름다움을 즐기게 해 줘."
    }
  ]
});