__loadLesson({
  "lesson": 6,
  "title": "Lesson 6: Use Smart, Live Safe",
  "version": "1.0",
  "build_date": "2026-07-12",
  "build_note": "v1.0 — 2학기 단어트랙 신규: 천재교육 Word List p.184~186 전수(이미지 판독 검증) + example은 교과서 본문/스크립트 채취. unit 필드=교과서 단원 태깅",
  "core_sentences": [],
  "grammar_rules": [],
  "questions": [],
  "vocab_drill": [
    {
      "id": "VD-L6-001",
      "unit": "L6",
      "word": "air fryer",
      "pos": "명사",
      "meaning": "에어프라이어",
      "example": "How do I use the air fryer?",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "어떻게 / 내가 사용하나요 / **에어프라이어**를?",
      "example_ko": "**에어프라이어**는 어떻게 사용해요?"
    },
    {
      "id": "VD-L6-002",
      "unit": "L6",
      "word": "apologize",
      "pos": "동사",
      "meaning": "사과하다",
      "example": "I apologized to him, and I deleted my post immediately.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "나는 / **사과했다** / 그에게, / 그리고 지웠다 / 내 게시물을 / 즉시.",
      "example_ko": "나는 그에게 **사과했고**, 내 게시물을 즉시 지웠어."
    },
    {
      "id": "VD-L6-003",
      "unit": "L6",
      "word": "click",
      "pos": "동사",
      "meaning": "(마우스를) 클릭하다",
      "example": "I clicked on it without thinking much.",
      "example_source": "본문 p.107",
      "example_ko_chunk": "나는 / **클릭했다** / 그것을 / 별생각 없이.",
      "example_ko": "나는 별생각 없이 그것을 **클릭했어**."
    },
    {
      "id": "VD-L6-004",
      "unit": "L6",
      "word": "comment",
      "pos": "명사",
      "meaning": "논평, 의견",
      "example": "Someone made a copy of the picture with bad comments.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "누군가 / 만들었다 / 그 사진의 복사본을 / 나쁜 **댓글(논평)**과 함께.",
      "example_ko": "누군가 나쁜 **댓글**을 달아 그 사진의 복사본을 만들었어."
    },
    {
      "id": "VD-L6-005",
      "unit": "L6",
      "word": "contact",
      "pos": "동사",
      "meaning": "연락하다",
      "example": "If you see the copies again, please contact us.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "만약 네가 본다면 / 그 복사본들을 다시, / **연락해** 주세요 / 우리에게.",
      "example_ko": "복사본을 또 보게 되면 저희에게 **연락해** 주세요."
    },
    {
      "id": "VD-L6-006",
      "unit": "L6",
      "word": "copy",
      "pos": "명사",
      "meaning": "복사(본)",
      "example": "Someone made a copy of the picture with bad comments.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "누군가 / 만들었다 / **복사본**을 / 그 사진의 / 나쁜 댓글과 함께.",
      "example_ko": "누군가 그 사진의 **복사본**을 만들어 나쁜 댓글을 달았어."
    },
    {
      "id": "VD-L6-007",
      "unit": "L6",
      "word": "credit card",
      "pos": "명사",
      "meaning": "신용 카드",
      "example": "Then, add your credit card.",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "그다음, / 등록하세요 / 당신의 **신용 카드**를.",
      "example_ko": "그다음 **신용 카드**를 등록하세요."
    },
    {
      "id": "VD-L6-008",
      "unit": "L6",
      "word": "dangerous",
      "pos": "형용사",
      "meaning": "위험한",
      "example": "It can be very dangerous.",
      "example_source": "본문 p.107",
      "example_ko_chunk": "그것은 / 될 수 있다 / 매우 **위험하게**.",
      "example_ko": "그건 매우 **위험할** 수 있어."
    },
    {
      "id": "VD-L6-009",
      "unit": "L6",
      "word": "decorate",
      "pos": "동사",
      "meaning": "꾸미다, 장식하다",
      "example": "You can decorate your photos with this app.",
      "example_source": "본문 p.102",
      "example_ko_chunk": "너는 / **꾸밀** 수 있다 / 네 사진들을 / 이 앱으로.",
      "example_ko": "이 앱으로 네 사진을 **꾸밀** 수 있어."
    },
    {
      "id": "VD-L6-010",
      "unit": "L6",
      "word": "delete",
      "pos": "동사",
      "meaning": "삭제하다",
      "example": "My brother wanted me to delete the picture of him.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "내 남동생은 / 원했다 / 내가 / **지우기를** / 자기 사진을.",
      "example_ko": "남동생은 내가 자기 사진을 **지우길** 원했어. (want+목적어+to부정사)"
    },
    {
      "id": "VD-L6-011",
      "unit": "L6",
      "word": "digital",
      "pos": "형용사",
      "meaning": "디지털의",
      "example": "Are you worried about your digital footprint?",
      "example_source": "본문 p.105",
      "example_ko_chunk": "걱정되나요 / 당신의 **디지털** 발자국이?",
      "example_ko": "당신의 **디지털** 발자국이 걱정되나요?"
    },
    {
      "id": "VD-L6-012",
      "unit": "L6",
      "word": "embarrassed",
      "pos": "형용사",
      "meaning": "당황스러운",
      "example": "The copy was spread here and there, and I was so embarrassed.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "그 복사본은 / 퍼졌다 / 여기저기에, / 그리고 나는 / 몹시 **당황스러웠다**.",
      "example_ko": "복사본이 여기저기 퍼져서 나는 몹시 **당황스러웠어**."
    },
    {
      "id": "VD-L6-013",
      "unit": "L6",
      "word": "erase",
      "pos": "동사",
      "meaning": "지우다",
      "example": "Do you want to erase it?",
      "example_source": "본문 p.105",
      "example_ko_chunk": "원하나요 / **지우기를** / 그것을?",
      "example_ko": "그것을 **지우고** 싶나요?"
    },
    {
      "id": "VD-L6-014",
      "unit": "L6",
      "word": "fill out",
      "pos": "숙어",
      "meaning": "작성하다",
      "example": "Then, I filled out my information to receive the gift.",
      "example_source": "본문 p.107",
      "example_ko_chunk": "그다음, / 나는 **작성했다** / 내 정보를 / 받기 위해 / 그 선물을.",
      "example_ko": "그다음 나는 선물을 받으려고 내 정보를 **작성했어**."
    },
    {
      "id": "VD-L6-015",
      "unit": "L6",
      "word": "footprint",
      "pos": "명사",
      "meaning": "발자국",
      "example": "Are you worried about your digital footprint?",
      "example_source": "본문 p.105",
      "example_ko_chunk": "걱정되나요 / 당신의 디지털 **발자국**이?",
      "example_ko": "당신의 디지털 **발자국**(인터넷에 남긴 흔적)이 걱정되나요?"
    },
    {
      "id": "VD-L6-016",
      "unit": "L6",
      "word": "for free",
      "pos": "숙어",
      "meaning": "무료로",
      "example": "It said that I could get a new smartphone for free.",
      "example_source": "본문 p.107",
      "example_ko_chunk": "그것은 말했다 / 내가 얻을 수 있다고 / 새 스마트폰을 / **무료로**.",
      "example_ko": "거기엔 새 스마트폰을 **무료로** 받을 수 있다고 쓰여 있었어."
    },
    {
      "id": "VD-L6-017",
      "unit": "L6",
      "word": "icon",
      "pos": "명사",
      "meaning": "(컴퓨터) 아이콘",
      "example": "Press the icon to save the song to your favorites.",
      "example_source": "본문 p.102",
      "example_ko_chunk": "누르세요 / 그 **아이콘**을 / 저장하려면 / 그 노래를 / 즐겨찾기에.",
      "example_ko": "노래를 즐겨찾기에 저장하려면 그 **아이콘**을 누르세요."
    },
    {
      "id": "VD-L6-018",
      "unit": "L6",
      "word": "immediately",
      "pos": "부사",
      "meaning": "즉시",
      "example": "I apologized to him, and I deleted my post immediately.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "나는 / 사과했다 / 그에게, / 그리고 지웠다 / 내 게시물을 / **즉시**.",
      "example_ko": "나는 그에게 사과했고, 게시물을 **즉시** 지웠어."
    },
    {
      "id": "VD-L6-019",
      "unit": "L6",
      "word": "instead of",
      "pos": "숙어",
      "meaning": "~ 대신에",
      "example": "Instead of getting a new smartphone, I have received useless emails.",
      "example_source": "본문 p.107 일부",
      "example_ko_chunk": "새 스마트폰을 받는 것 **대신에**, / 나는 받아 왔다 / 쓸모없는 이메일들을.",
      "example_ko": "새 스마트폰 **대신에** 나는 쓸모없는 이메일만 받아 왔어."
    },
    {
      "id": "VD-L6-020",
      "unit": "L6",
      "word": "laundry",
      "pos": "명사",
      "meaning": "세탁소",
      "example": "A laundry washes your clothes.",
      "example_source": "본문 p.105 응용",
      "example_ko_chunk": "**세탁소**는 / 세탁한다 / 너의 옷을.",
      "example_ko": "**세탁소**는 옷을 빨아 주는 곳이야. (본문의 Happy Digital Laundry = 디지털 세탁소)"
    },
    {
      "id": "VD-L6-021",
      "unit": "L6",
      "word": "link",
      "pos": "명사·동사",
      "meaning": "(컴퓨터) 링크 / 연결하다",
      "example": "Don't click on ads or links from unknown sources.",
      "example_source": "본문 p.107 일부",
      "example_ko_chunk": "클릭하지 마세요 / 광고나 **링크**를 / 모르는 출처에서 온.",
      "example_ko": "모르는 출처의 광고나 **링크**는 클릭하지 마."
    },
    {
      "id": "VD-L6-022",
      "unit": "L6",
      "word": "microphone",
      "pos": "명사",
      "meaning": "마이크",
      "example": "Second, press the microphone icon and wait for a while.",
      "example_source": "본문 p.102 (Enjoy the Clip 스크립트)",
      "example_ko_chunk": "두 번째로, / 누르세요 / **마이크** 아이콘을 / 그리고 기다리세요 / 잠시.",
      "example_ko": "두 번째로 **마이크** 아이콘을 누르고 잠시 기다리세요."
    },
    {
      "id": "VD-L6-023",
      "unit": "L6",
      "word": "password",
      "pos": "명사",
      "meaning": "비밀번호",
      "example": "You should use strong passwords online.",
      "example_source": "본문 p.109",
      "example_ko_chunk": "너는 / 사용해야 한다 / 강력한 **비밀번호**를 / 온라인에서.",
      "example_ko": "온라인에서는 강력한 **비밀번호**를 써야 해."
    },
    {
      "id": "VD-L6-024",
      "unit": "L6",
      "word": "pay",
      "pos": "동사",
      "meaning": "지불하다",
      "example": "Then, pay on the next page.",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "그다음, / **결제하세요** / 다음 페이지에서.",
      "example_ko": "그다음 페이지에서 **결제하세요(돈을 내세요)**."
    },
    {
      "id": "VD-L6-025",
      "unit": "L6",
      "word": "personal",
      "pos": "형용사",
      "meaning": "개인의, 개인적인",
      "example": "I think that my personal information was shared.",
      "example_source": "본문 p.107",
      "example_ko_chunk": "나는 생각한다 / 내 **개인** 정보가 / 공유되었다고.",
      "example_ko": "내 **개인** 정보가 퍼진 것 같아."
    },
    {
      "id": "VD-L6-026",
      "unit": "L6",
      "word": "record",
      "pos": "명사·동사",
      "meaning": "기록 / 기록하다",
      "example": "We checked your online records and found the ad.",
      "example_source": "본문 p.107",
      "example_ko_chunk": "우리는 / 확인했다 / 당신의 온라인 **기록**을 / 그리고 찾았다 / 그 광고를.",
      "example_ko": "저희가 당신의 온라인 **기록**을 확인해서 그 광고를 찾았어요."
    },
    {
      "id": "VD-L6-027",
      "unit": "L6",
      "word": "remove",
      "pos": "동사",
      "meaning": "없애다",
      "example": "I want to remove them all.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "나는 / 원한다 / **없애기를** / 그것들 전부.",
      "example_ko": "나는 그것들을 전부 **없애고** 싶어."
    },
    {
      "id": "VD-L6-028",
      "unit": "L6",
      "word": "salad",
      "pos": "명사",
      "meaning": "샐러드",
      "example": "Making cheese salad is very easy.",
      "example_source": "교과서 p.114 (Review 스크립트)",
      "example_ko_chunk": "만드는 것은 / 치즈 **샐러드**를 / 아주 쉽다.",
      "example_ko": "치즈 **샐러드** 만들기는 아주 쉬워."
    },
    {
      "id": "VD-L6-029",
      "unit": "L6",
      "word": "screen",
      "pos": "명사",
      "meaning": "화면",
      "example": "First, select your hamburger on the screen.",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "먼저, / 고르세요 / 당신의 햄버거를 / **화면**에서.",
      "example_ko": "먼저 **화면**에서 햄버거를 고르세요."
    },
    {
      "id": "VD-L6-030",
      "unit": "L6",
      "word": "seat",
      "pos": "명사",
      "meaning": "자리, 좌석",
      "example": "Select the time and seat.",
      "example_source": "본문 p.100 (Listen & Talk)",
      "example_ko_chunk": "고르세요 / 시간과 **좌석**을.",
      "example_ko": "시간과 **좌석**을 고르세요."
    },
    {
      "id": "VD-L6-031",
      "unit": "L6",
      "word": "select",
      "pos": "동사",
      "meaning": "선택하다",
      "example": "First, select your hamburger on the screen.",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "먼저, / **선택하세요** / 당신의 햄버거를 / 화면에서.",
      "example_ko": "먼저 화면에서 햄버거를 **선택하세요**."
    },
    {
      "id": "VD-L6-032",
      "unit": "L6",
      "word": "set",
      "pos": "동사",
      "meaning": "설정하다, (상 등을) 차리다",
      "example": "Lastly, set the time to 20 minutes and press the start button.",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "마지막으로, / **설정하세요** / 시간을 / 20분으로 / 그리고 누르세요 / 시작 버튼을.",
      "example_ko": "마지막으로 시간을 20분으로 **설정하고** 시작 버튼을 누르세요."
    },
    {
      "id": "VD-L6-033",
      "unit": "L6",
      "word": "sign up",
      "pos": "숙어",
      "meaning": "등록하다",
      "example": "First, sign up for our app.",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "먼저, / **등록하세요(가입하세요)** / 우리 앱에.",
      "example_ko": "먼저 우리 앱에 **가입하세요(등록하세요)**."
    },
    {
      "id": "VD-L6-034",
      "unit": "L6",
      "word": "source",
      "pos": "명사",
      "meaning": "출처",
      "example": "Don't click on ads or links from unknown sources.",
      "example_source": "본문 p.107 일부",
      "example_ko_chunk": "클릭하지 마세요 / 광고나 링크를 / 알 수 없는 **출처**에서 온.",
      "example_ko": "알 수 없는 **출처**의 광고나 링크는 클릭하지 마."
    },
    {
      "id": "VD-L6-035",
      "unit": "L6",
      "word": "spread",
      "pos": "동사",
      "meaning": "퍼뜨리다",
      "example": "The copy was spread here and there, and I was so embarrassed.",
      "example_source": "본문 p.106",
      "example_ko_chunk": "그 복사본은 / **퍼졌다** / 여기저기에, / 그리고 나는 / 몹시 당황스러웠다.",
      "example_ko": "복사본이 여기저기 **퍼져서** 나는 몹시 당황스러웠어."
    },
    {
      "id": "VD-L6-036",
      "unit": "L6",
      "word": "sticker",
      "pos": "명사",
      "meaning": "스티커",
      "example": "Then, put some stickers or write something on it.",
      "example_source": "본문 p.102",
      "example_ko_chunk": "그다음, / 붙이세요 / **스티커**를 / 또는 쓰세요 / 무언가를 / 그 위에.",
      "example_ko": "그다음 **스티커**를 붙이거나 그 위에 뭔가를 써 보세요."
    },
    {
      "id": "VD-L6-037",
      "unit": "L6",
      "word": "subject",
      "pos": "명사",
      "meaning": "주제, 제목",
      "example": "The subject of my email is 'Need Help with My Headphones.'",
      "example_source": "본문 p.112 응용",
      "example_ko_chunk": "**제목**은 / 내 이메일의 / '헤드폰 도움 요청'이다.",
      "example_ko": "내 이메일의 **제목**은 '헤드폰 도움 요청'이야."
    },
    {
      "id": "VD-L6-038",
      "unit": "L6",
      "word": "tag",
      "pos": "동사",
      "meaning": "(전자 기기를) ~에 대다",
      "example": "Lastly, tag your phone on the bike.",
      "example_source": "본문 p.100 (Listen & Talk 스크립트)",
      "example_ko_chunk": "마지막으로, / **대세요(태그하세요)** / 당신의 폰을 / 자전거에.",
      "example_ko": "마지막으로 폰을 자전거에 **대세요(태그하세요)**."
    },
    {
      "id": "VD-L6-039",
      "unit": "L6",
      "word": "unknown",
      "pos": "형용사",
      "meaning": "알려지지 않은",
      "example": "I have received useless emails and phone calls from unknown numbers.",
      "example_source": "본문 p.107 일부",
      "example_ko_chunk": "나는 / 받아 왔다 / 쓸모없는 이메일과 전화를 / **모르는** 번호로부터.",
      "example_ko": "나는 **모르는** 번호로부터 쓸모없는 이메일과 전화를 받아 왔어."
    },
    {
      "id": "VD-L6-040",
      "unit": "L6",
      "word": "useless",
      "pos": "형용사",
      "meaning": "쓸모없는",
      "example": "I have received useless emails and phone calls from unknown numbers.",
      "example_source": "본문 p.107 일부",
      "example_ko_chunk": "나는 / 받아 왔다 / **쓸모없는** 이메일과 전화를 / 모르는 번호로부터.",
      "example_ko": "나는 모르는 번호로부터 **쓸모없는** 이메일과 전화를 받아 왔어."
    }
  ]
});