__loadLesson({
  "lesson": 5,
  "title": "Lesson 5: From Your Interest to Future Jobs",
  "version": "1.0",
  "build_date": "2026-07-12",
  "build_note": "v1.0 — 2학기 단어트랙 신규: 천재교육 Word List p.184~186 전수(이미지 판독 검증) + example은 교과서 본문/스크립트 채취. unit 필드=교과서 단원 태깅",
  "core_sentences": [],
  "grammar_rules": [],
  "questions": [],
  "vocab_drill": [
    {
      "id": "VD-L5-001",
      "unit": "L5",
      "word": "above all",
      "pos": "숙어",
      "meaning": "무엇보다도",
      "example": "Above all, I love ice hockey.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "**무엇보다도**, / 나는 사랑한다 / 아이스하키를.",
      "example_ko": "**무엇보다도** 나는 아이스하키를 사랑해."
    },
    {
      "id": "VD-L5-002",
      "unit": "L5",
      "word": "advertisement",
      "pos": "명사",
      "meaning": "광고 (= ad)",
      "example": "They want my clients in their advertisements.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "그들은 / 원한다 / 내 고객들이 / 그들의 **광고**에 (나오기를).",
      "example_ko": "그들은 내 고객들이 자기네 **광고**에 나오기를 원해."
    },
    {
      "id": "VD-L5-003",
      "unit": "L5",
      "word": "advertising company",
      "pos": "명사",
      "meaning": "광고 회사",
      "example": "I often receive phone calls from advertising companies.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "나는 / 자주 받는다 / 전화를 / **광고 회사**들로부터.",
      "example_ko": "나는 **광고 회사**들에게서 자주 전화를 받아.",
      "inflections": [
        "advertising companies"
      ]
    },
    {
      "id": "VD-L5-004",
      "unit": "L5",
      "word": "against",
      "pos": "전치사",
      "meaning": "~에 맞서, ~에 반대하여",
      "example": "Our team is going to play against the Ice Lions this Saturday.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "우리 팀은 / 경기할 것이다 / Ice Lions**에 맞서** / 이번 토요일에.",
      "example_ko": "우리 팀은 이번 토요일에 Ice Lions**를 상대로(맞서)** 경기해."
    },
    {
      "id": "VD-L5-005",
      "unit": "L5",
      "word": "agent",
      "pos": "명사",
      "meaning": "에이전트, 대리인",
      "example": "Do you like your job as a sports agent?",
      "example_source": "본문 p.88",
      "example_ko_chunk": "좋아하나요 / 당신의 일을 / 스포츠 **에이전트**로서의?",
      "example_ko": "스포츠 **에이전트**로서 하는 일이 마음에 드시나요?"
    },
    {
      "id": "VD-L5-006",
      "unit": "L5",
      "word": "analyze",
      "pos": "동사",
      "meaning": "분석하다",
      "example": "I watched the Ice Lions' games and analyzed their shots.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "나는 / 봤다 / Ice Lions의 경기를 / 그리고 **분석했다** / 그들의 슛을.",
      "example_ko": "나는 Ice Lions의 경기를 보고 그들의 슛을 **분석했어**."
    },
    {
      "id": "VD-L5-007",
      "unit": "L5",
      "word": "article",
      "pos": "명사",
      "meaning": "(신문, 잡지의) 기사",
      "example": "I had to write an article and edit it very quickly.",
      "example_source": "본문 p.87",
      "example_ko_chunk": "나는 / 써야 했다 / **기사**를 / 그리고 고쳐야 했다 / 아주 빨리.",
      "example_ko": "나는 **기사**를 쓰고 아주 빨리 고쳐야 했어."
    },
    {
      "id": "VD-L5-008",
      "unit": "L5",
      "word": "business",
      "pos": "명사",
      "meaning": "사업",
      "example": "I love sports, and I enjoy everything about business.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "나는 사랑한다 / 스포츠를, / 그리고 즐긴다 / 모든 것을 / **사업**에 관한.",
      "example_ko": "나는 스포츠를 사랑하고, **사업**에 관한 모든 것을 즐겨."
    },
    {
      "id": "VD-L5-009",
      "unit": "L5",
      "word": "career",
      "pos": "명사",
      "meaning": "직업, 경력",
      "example": "If you do, you can have a career in sports.",
      "example_source": "본문 p.87",
      "example_ko_chunk": "만약 그렇다면, / 너는 가질 수 있다 / **직업**을 / 스포츠 분야에서.",
      "example_ko": "(스포츠를 사랑한다면) 너는 스포츠 분야에서 **직업**을 가질 수 있어."
    },
    {
      "id": "VD-L5-010",
      "unit": "L5",
      "word": "cheerleader",
      "pos": "명사",
      "meaning": "치어리더",
      "example": "The cheerleaders are dancing for the team.",
      "example_source": "본문 p.81 응용",
      "example_ko_chunk": "**치어리더**들이 / 춤추고 있다 / 팀을 위해.",
      "example_ko": "**치어리더**들이 팀을 위해 춤추고 있어."
    },
    {
      "id": "VD-L5-011",
      "unit": "L5",
      "word": "chef",
      "pos": "명사",
      "meaning": "요리사",
      "example": "The chef for the sports team prepares their dinner.",
      "example_source": "본문 p.95 응용",
      "example_ko_chunk": "**요리사**는 / 스포츠 팀의 / 준비한다 / 그들의 저녁을.",
      "example_ko": "스포츠 팀 **요리사**는 선수들의 저녁을 준비해."
    },
    {
      "id": "VD-L5-012",
      "unit": "L5",
      "word": "client",
      "pos": "명사",
      "meaning": "의뢰인, 고객",
      "example": "When my clients have a new contract to sign, I check it carefully.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "내 **고객**들이 / 가질 때 / 새 계약서를 / 서명할, / 나는 / 확인한다 / 그것을 꼼꼼히.",
      "example_ko": "내 **고객**들이 서명할 새 계약서가 생기면, 나는 그것을 꼼꼼히 확인해."
    },
    {
      "id": "VD-L5-013",
      "unit": "L5",
      "word": "condition",
      "pos": "명사",
      "meaning": "상태",
      "example": "I have a meeting with the team leader about the players' health conditions.",
      "example_source": "본문 p.95",
      "example_ko_chunk": "나는 / 회의를 한다 / 팀 리더와 / 선수들의 건강 **상태**에 대해.",
      "example_ko": "나는 선수들의 건강 **상태**에 대해 팀 리더와 회의를 해."
    },
    {
      "id": "VD-L5-014",
      "unit": "L5",
      "word": "contract",
      "pos": "명사",
      "meaning": "계약, 계약서",
      "example": "I do my best to make the contract fair for them.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "나는 / 최선을 다한다 / 만들려고 / **계약**을 / 공정하게 / 그들에게.",
      "example_ko": "나는 그들에게 **계약**이 공정하도록 최선을 다해."
    },
    {
      "id": "VD-L5-015",
      "unit": "L5",
      "word": "data",
      "pos": "명사",
      "meaning": "데이터, 정보",
      "example": "I'm happy to use my data to help our team.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "나는 / 기쁘다 / 사용해서 / 내 **데이터**를 / 돕기 위해 / 우리 팀을.",
      "example_ko": "내 **데이터**로 우리 팀을 도울 수 있어서 기뻐."
    },
    {
      "id": "VD-L5-016",
      "unit": "L5",
      "word": "deal",
      "pos": "명사",
      "meaning": "거래, (사업상의) 합의",
      "example": "Then, I try to get the best deal for my clients.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "그다음, / 나는 노력한다 / 얻으려고 / 최고의 **거래**를 / 내 고객들을 위해.",
      "example_ko": "그다음 나는 고객들을 위해 최고의 **거래**를 얻으려고 노력해."
    },
    {
      "id": "VD-L5-017",
      "unit": "L5",
      "word": "difficulty",
      "pos": "명사",
      "meaning": "어려움, 고난",
      "example": "Difficulties make me strong.",
      "example_source": "본문 p.92 (Focus on Language)",
      "example_ko_chunk": "**어려움**들은 / 만든다 / 나를 / 강하게.",
      "example_ko": "**어려움**은 나를 강하게 만들어. (make+목적어+형용사)",
      "inflections": [
        "difficulties"
      ]
    },
    {
      "id": "VD-L5-018",
      "unit": "L5",
      "word": "edit",
      "pos": "동사",
      "meaning": "편집하다",
      "example": "I had to write an article and edit it very quickly.",
      "example_source": "본문 p.87",
      "example_ko_chunk": "나는 / 써야 했다 / 기사를 / 그리고 **편집해야(고쳐야)** 했다 / 아주 빨리.",
      "example_ko": "나는 기사를 쓰고 아주 빨리 **편집해야(고쳐야)** 했어."
    },
    {
      "id": "VD-L5-019",
      "unit": "L5",
      "word": "fair",
      "pos": "형용사",
      "meaning": "온당한, 공정한",
      "example": "I do my best to make the contract fair for them.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "나는 / 최선을 다한다 / 만들려고 / 계약을 / **공정하게** / 그들에게.",
      "example_ko": "나는 계약이 그들에게 **공정하도록** 최선을 다해. (make+목적어+형용사)"
    },
    {
      "id": "VD-L5-020",
      "unit": "L5",
      "word": "focus",
      "pos": "동사",
      "meaning": "집중하다",
      "example": "I like to focus on myself when I exercise.",
      "example_source": "본문 p.82 (Listen & Talk)",
      "example_ko_chunk": "나는 / 좋아한다 / **집중하는** 것을 / 나 자신에게 / 운동할 때.",
      "example_ko": "나는 운동할 때 나 자신에게 **집중하는** 걸 좋아해."
    },
    {
      "id": "VD-L5-021",
      "unit": "L5",
      "word": "ice hockey",
      "pos": "명사",
      "meaning": "아이스하키",
      "example": "Above all, I love ice hockey.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "무엇보다도, / 나는 사랑한다 / **아이스하키**를.",
      "example_ko": "무엇보다도 나는 **아이스하키**를 사랑해."
    },
    {
      "id": "VD-L5-022",
      "unit": "L5",
      "word": "individual",
      "pos": "형용사",
      "meaning": "각각의, 개인의",
      "example": "I prefer team sports to individual sports.",
      "example_source": "본문 p.82 (Listen & Talk)",
      "example_ko_chunk": "나는 / 더 좋아한다 / 팀 스포츠를 / **개인** 스포츠보다.",
      "example_ko": "나는 **개인** 스포츠보다 팀 스포츠를 더 좋아해."
    },
    {
      "id": "VD-L5-023",
      "unit": "L5",
      "word": "journalist",
      "pos": "명사",
      "meaning": "(신문 등의) 기자, 저널리스트",
      "example": "Can you tell me why you became a sports journalist?",
      "example_source": "본문 p.80",
      "example_ko_chunk": "말해 줄 수 있나요 / 왜 당신이 되었는지 / 스포츠 **기자**가?",
      "example_ko": "왜 스포츠 **기자**가 되셨는지 말해 줄 수 있나요? (간접의문문)"
    },
    {
      "id": "VD-L5-024",
      "unit": "L5",
      "word": "let in",
      "pos": "숙어",
      "meaning": "들어오게 하다",
      "example": "They let in 70 percent of the shots from the left side.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "그들은 / **들어오게 했다(허용했다)** / 슛의 70퍼센트를 / 왼쪽에서 오는.",
      "example_ko": "그들은 왼쪽에서 오는 슛의 70%를 **들어오게 했어(먹혔어)**."
    },
    {
      "id": "VD-L5-025",
      "unit": "L5",
      "word": "logic",
      "pos": "명사",
      "meaning": "논리",
      "example": "If you like math, you may be smart in logic.",
      "example_source": "스크립트 p.169 응용 (Enjoy the Clip)",
      "example_ko_chunk": "만약 네가 좋아한다면 / 수학을, / 너는 똑똑할 수 있다 / **논리**에.",
      "example_ko": "수학을 좋아한다면 너는 **논리**가 뛰어난 사람일 수 있어."
    },
    {
      "id": "VD-L5-026",
      "unit": "L5",
      "word": "passion",
      "pos": "명사",
      "meaning": "열정",
      "example": "I've always had a passion for sports and writing.",
      "example_source": "본문 p.86",
      "example_ko_chunk": "나는 / 항상 가져 왔다 / **열정**을 / 스포츠와 글쓰기에 대한.",
      "example_ko": "나는 늘 스포츠와 글쓰기에 **열정**이 있었어."
    },
    {
      "id": "VD-L5-027",
      "unit": "L5",
      "word": "prefer",
      "pos": "동사",
      "meaning": "~을/를 더 좋아하다, 선호하다",
      "example": "I prefer math to English.",
      "example_source": "본문 p.82 (Listen & Talk)",
      "example_ko_chunk": "나는 / **더 좋아한다** / 수학을 / 영어보다.",
      "example_ko": "나는 영어보다 수학을 **더 좋아해**. (prefer A to B)"
    },
    {
      "id": "VD-L5-028",
      "unit": "L5",
      "word": "prepare",
      "pos": "동사",
      "meaning": "준비하다",
      "example": "I prepare their dinner.",
      "example_source": "본문 p.95",
      "example_ko_chunk": "나는 / **준비한다** / 그들의 저녁을.",
      "example_ko": "나는 그들의 저녁을 **준비해**."
    },
    {
      "id": "VD-L5-029",
      "unit": "L5",
      "word": "press conference",
      "pos": "명사",
      "meaning": "기자 회견",
      "example": "After the game, I went to the press conference with other journalists.",
      "example_source": "본문 p.87",
      "example_ko_chunk": "경기 후에, / 나는 갔다 / **기자 회견**에 / 다른 기자들과 함께.",
      "example_ko": "경기가 끝난 뒤 나는 다른 기자들과 **기자 회견**에 갔어."
    },
    {
      "id": "VD-L5-030",
      "unit": "L5",
      "word": "pyramid",
      "pos": "명사",
      "meaning": "피라미드",
      "example": "Let's play pyramid bingo!",
      "example_source": "본문 p.85 (Play with Expressions)",
      "example_ko_chunk": "하자 / **피라미드** 빙고를!",
      "example_ko": "**피라미드** 빙고 하자!"
    },
    {
      "id": "VD-L5-031",
      "unit": "L5",
      "word": "receive",
      "pos": "동사",
      "meaning": "받다",
      "example": "I often receive phone calls from advertising companies.",
      "example_source": "본문 p.88",
      "example_ko_chunk": "나는 / 자주 **받는다** / 전화를 / 광고 회사들로부터.",
      "example_ko": "나는 광고 회사들에게서 전화를 자주 **받아**."
    },
    {
      "id": "VD-L5-032",
      "unit": "L5",
      "word": "reporter",
      "pos": "명사",
      "meaning": "기자, 리포터",
      "example": "The reporter in Picture B is taking notes.",
      "example_source": "본문 p.81",
      "example_ko_chunk": "**기자**는 / 그림 B의 / 메모하고 있다.",
      "example_ko": "그림 B의 **기자**는 메모를 하고 있어."
    },
    {
      "id": "VD-L5-033",
      "unit": "L5",
      "word": "rush hour",
      "pos": "명사",
      "meaning": "혼잡 시간대, 러시아워",
      "example": "The bus is not faster during rush hour.",
      "example_source": "본문 p.82 (Listen & Talk)",
      "example_ko_chunk": "버스는 / 더 빠르지 않다 / **혼잡 시간대**에는.",
      "example_ko": "**혼잡 시간대(러시아워)**에는 버스가 더 빠르지 않아."
    },
    {
      "id": "VD-L5-034",
      "unit": "L5",
      "word": "score",
      "pos": "동사",
      "meaning": "득점하다",
      "example": "Let's score goals!",
      "example_source": "본문 p.93 (Play with Language)",
      "example_ko_chunk": "하자 / **득점**을 / 골로!",
      "example_ko": "골을 넣어 **득점하자**!"
    },
    {
      "id": "VD-L5-035",
      "unit": "L5",
      "word": "self",
      "pos": "명사",
      "meaning": "자아, 자신",
      "example": "You can be smart in music, logic, nature, or self.",
      "example_source": "스크립트 p.169 응용 (Enjoy the Clip)",
      "example_ko_chunk": "너는 / 똑똑할 수 있다 / 음악, 논리, 자연, / 혹은 **자아(자신)** 영역에서.",
      "example_ko": "너는 음악·논리·자연, 혹은 **자아(자기 이해)** 영역에서 똑똑할 수 있어."
    },
    {
      "id": "VD-L5-036",
      "unit": "L5",
      "word": "serve",
      "pos": "동사",
      "meaning": "(음식을) 제공하다, 차려 주다",
      "example": "I check all the dishes before they are served.",
      "example_source": "본문 p.95",
      "example_ko_chunk": "나는 / 확인한다 / 모든 요리를 / 그것들이 **제공되기** 전에.",
      "example_ko": "나는 요리가 **차려지기(제공되기)** 전에 전부 확인해."
    },
    {
      "id": "VD-L5-037",
      "unit": "L5",
      "word": "shot",
      "pos": "명사",
      "meaning": "(축구 등) 슛",
      "example": "They let in 70 percent of the shots from the left side.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "그들은 / 들어오게 했다 / **슛**의 70퍼센트를 / 왼쪽에서 오는.",
      "example_ko": "그들은 왼쪽에서 오는 **슛**의 70%를 먹혔어."
    },
    {
      "id": "VD-L5-038",
      "unit": "L5",
      "word": "statistician",
      "pos": "명사",
      "meaning": "통계 전문가",
      "example": "A sports statistician is someone who collects data and studies numbers about sports games.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "스포츠 **통계 전문가**는 / 사람이다 / 데이터를 모으고 / 숫자를 연구하는 / 스포츠 경기에 대한.",
      "example_ko": "스포츠 **통계 전문가**는 경기 데이터를 모으고 숫자를 연구하는 사람이야."
    },
    {
      "id": "VD-L5-039",
      "unit": "L5",
      "word": "subway",
      "pos": "명사",
      "meaning": "지하철",
      "example": "Let's take the subway together.",
      "example_source": "본문 p.82 (Listen & Talk)",
      "example_ko_chunk": "타자 / **지하철**을 / 함께.",
      "example_ko": "같이 **지하철** 타자."
    },
    {
      "id": "VD-L5-040",
      "unit": "L5",
      "word": "weak",
      "pos": "형용사",
      "meaning": "약한",
      "example": "This showed their left side was weak.",
      "example_source": "본문 p.89",
      "example_ko_chunk": "이것은 / 보여 줬다 / 그들의 왼쪽이 / **약하다는** 것을.",
      "example_ko": "이건 그들의 왼쪽이 **약하다**는 걸 보여 줬어."
    }
  ]
});